#! /bin/sh
# Set the CPU Frequency Scaling governor to "schedutil"/"powersave" where available
set -eu

FIRSTCPU=`cut -f1 -d- /sys/devices/system/cpu/online`
AVAILABLE="/sys/devices/system/cpu/cpu$FIRSTCPU/cpufreq/scaling_available_governors"
DOWN_FACTOR="/sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor"

[ -f $AVAILABLE ] || exit 0

read governors < $AVAILABLE
case $governors in
        *schedutil*)
                GOVERNOR="schedutil"
                break
                ;;
       *powersave*)
                GOVERNOR="powersave"
                break
                ;;
        *)
                exit 0
                ;;
esac

[ -n "${GOVERNOR:-}" ] || exit 0

echo "Setting $GOVERNOR scheduler for all CPUs"

for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
do
        [ -f $CPUFREQ ] || continue
        echo -n $GOVERNOR > $CPUFREQ
done

