theme = "dark_plus"

[editor]
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
true-color = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "bar"

[editor.indent-guides]
character = "┆"
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.inline-diagnostics]
cursor-line = "hint" # Show inline diagnostics when the cursor is on the line

[editor.whitespace]
render = "all"

[keys.normal]
C-n = ["search_selection", "extend_search_next"]

