#!/usr/bin/bash

if ! type "zxcvbn" &> /dev/null; then
  printf "%s\n" "pip install zxcvbn"
  exit 1
fi

if ! type "jq" &> /dev/null; then
  printf "%s\n" "apt install jq"
  exit 1
fi


arguments=("${@: 1}")

if [ -z "$arguments" ]; then
    echo "Usage: checkpassword <password>"
    exit 1
fi

echo ${arguments[@]} | zxcvbn | jq
