#!/usr/bin/env ruby
# frozen_string_literal: true

require 'net/http'
require 'json'

issue = ARGV[0]

unless issue
  puts 'Please provide an issue number'

  exit 1
end

issue = issue.downcase

jira_user = ENV['JIRA_USER']
jira_token = ENV['JIRA_TOKEN']

unless jira_user && jira_token
  puts 'please set JIRA_USER and JIRA_TOKEN'

  exit 1
end

uri = URI("https://femtasy.atlassian.net/rest/api/2/issue/#{issue}")

req = Net::HTTP::Get.new(uri.request_uri)

req.basic_auth jira_user, jira_token

res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
  http.request(req)
end

body = JSON.parse(res.body)

summary = body['fields']['summary']
          .downcase
          .strip # trim spaces
          .gsub(/\W+/, '-') # non alphabetical chars to -
          .gsub(/-+/, '-') # remove duplicated -

if issue =~ /^fm-/i
  # remove project preix
  code = issue.gsub(/^\w+-/, '')
else
  code = issue
end

`git co -b #{code}-#{summary}`
