#!/usr/bin/env node
const https = require('https');
const { execSync } = require('child_process');

const issue = process.argv[2];

if (!issue) {
  console.log('Please provide an issue number');
  process.exit(1);
}

const issueLowerCase = issue.toLowerCase();

const jiraUser = process.env.JIRA_USER;
const jiraToken = process.env.JIRA_TOKEN;
const jiraApiUri = process.env.JIRA_ISSUE_API_URI

if (!jiraUser || !jiraToken) {
  console.log('Please set JIRA_USER and JIRA_TOKEN environment variables');
  process.exit(1);
}

const uri = `${jiraApiUri}/${issueLowerCase}`;

const options = {
  method: 'GET',
  headers: {
    'Authorization': 'Basic ' + Buffer.from(`${jiraUser}:${jiraToken}`).toString('base64')
  }
};

https.get(uri, options, (res) => {
  let data = '';

  res.on('data', (chunk) => {
    data += chunk;
  });

  res.on('end', () => {
    const body = JSON.parse(data);
    const summary = body.fields.summary
      .toLowerCase()
      .trim()
      .replace(/\W+/g, '-')
      .replace(/-+/g, '-');

    const code = /^fm-/i.test(issueLowerCase) ? issueLowerCase.replace(/^\w+-/, '') : issueLowerCase;

    const command = `git checkout -b ${code}-${summary}`;
    execSync(command, { stdio: 'inherit' });
  });
}).on('error', (error) => {
  console.error(error);
});
