# use UTF-8 everywhere
export LANG=en_US.UTF-8

# specify location of kshrc
export ENV=$HOME/.kshrc

# load Xresources file
xrdb -merge $HOME/.Xresources

# set your background color
xsetroot -solid dimgray

# xidle will lock your display after a period of inactivity
xidle &

# disable system beep
xset b off

# use caps lock as ctrl key
setxkbmap -option ctrl:nocaps

# start cwm!
# exec cwm

# start i3-gaps
exec i3
