# GNU and BSD (macOS) ls flags aren't compatible
ls --version &>/dev/null
if [ $? -eq 0 ]; then
  lsflags="--color --group-directories-first -F"
else
  lsflags="-GF"
  export CLICOLOR=1
fi


# dircolors
eval "$(dircolors -b)"

### Aliases
# ls
alias ls="ls ${lsflags}"
alias la="ls -a"
alias ll="ls -al"
alias lr="ls -lRh"
alias lt="ls -ltrh"
alias cat="bat"
alias fd="fdfind"
# directories
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -iv"
alias rmf="rm -ivrf"
alias mkdir="mkdir -p"
alias less="less -R"

# History settings
HISTFILE=~/.zhistory
HISTSIZ=10000
SAVEHIST=10000
setopt append_history           # allow multiple sessions to append to one history
setopt bang_hist                # treat ! special during command expansion
setopt hist_expire_dups_first   # expire duplicates first when trimming history
setopt hist_find_no_dups        # When searching history, don't repeat
setopt hist_ignore_dups         # ignore duplicate entries of previous event
setopt hist_ignore_space        # prefix command with a space to skip it's recording
setopt hist_reduce_blanks       # Remove extra blanks from each command added to history
setopt hist_no_store		        # Remove the history (fc -l) command from the history list when invoked.
setopt hist_save_no_dups
setopt hist_verify              # Don't execute immediately upon history expansion
setopt inc_append_history       # Write to history file immediately, not when shell quits
setopt share_history            # Share history among all sessions

# Tab completion
unsetopt menu_complete          # do not autoselect the first completion entry
setopt auto_menu                # show menu completion on succesive tab press
setopt complete_in_word         # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt autocd                   # cd to a folder just by typing it's name

zstyle ':completion:*' verbose yes
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*:*:*:*:*' menu select
zmodload zsh/complist

# vim navigation keys
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

autoload -Uz compinit && compinit

# MISC
setopt interactive_comments     # allow # comments in shell; good for copy/paste
unsetopt BEEP                   # sweet silence

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# asdf-vm
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

