# GNU and BSD (macOS) ls flags aren't compatible
if [[ $OSTYPE == "linux-gnu" ]]; then
  eval "$(dircolors -b)"
  alias ls="ls -Fh --color=auto"

 if command -v fdfind &> /dev/null; then
    alias fd="fdfind"
 fi

 if command -v batcat &> /dev/null; then
    alias cat="batcat"
 elif  command -v bat &> /dev/null; then
    alias cat="bat"
 fi
else
  alias ls="ls -GF"
  export CLICOLOR=1
fi

# editor
alias vi="nvim"

alias la="ls -a"
alias ll="ls -al"
alias lr="ls -lR"
alias lt="du -sh * | sort -h"

# directories
alias cp="cp -i"
alias mv="mv -i"
alias rmf="rm -ivrf"
alias mkdir="mkdir -p"
alias less="less -R"

# git
alias gc="git commit -m"
